version: '2.2'

services:
  sink:
    build: ./cqrs-sink
    ports:
      - 8081:8081
    links:
      - db
      - kafka

  source:
    build: ./cqrs-source
    ports:
      - 8080:8080
    links:
      - db
      - kafka

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypwd
      - POSTGRES_DB=mydb

  zookeeper:
    image: confluent/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: confluent/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092