version: "2"

services:
  sink:
    build: ./cqrs-sink
    ports:
      - 8081:8081
    links:
      - mysql
      - kafka

  source:
    build: ./cqrs-source
    ports:
      - 8080:8080
    links:
      - mysql
      - kafka

  mysql:
      image: mysql
      ports:
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=myuser
       - MYSQL_PASSWORD=mypwd

  zookeeper:
    image: confluent/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: confluent/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092